import { type IndustryBucket } from './industry-buckets'

// SIC (4-digit) → primary bucket. Numbers are SEC-published industry codes.
// NOTE: SIC 1311 = "Crude Petroleum and Natural Gas" (energy, not mining).
// User spec listed it twice (energy + materials/mining) — kept the energy
// mapping because mis-routing oil & gas majors to mining would break
// Iran-Crisis recall. SIC 1040 = Gold Mining handles the mining bucket.
export const SIC_TO_BUCKET: Record<number, IndustryBucket> = {
  // Energy
  1311: 'energy/oil_gas',
  1381: 'energy/services',
  1382: 'energy/services',
  1389: 'energy/services',
  2911: 'energy/refining',
  4412: 'energy/shipping',
  4922: 'energy/midstream',
  4923: 'energy/midstream',
  4924: 'energy/lng',

  // Materials
  1040: 'materials/mining',
  1041: 'materials/mining',
  1044: 'materials/mining',
  1090: 'materials/mining',
  2800: 'materials/chemicals',
  2812: 'materials/chemicals',
  2820: 'materials/chemicals',
  2821: 'materials/chemicals',
  2860: 'materials/chemicals',
  2870: 'materials/agriculture',
  2899: 'materials/chemicals',
  3310: 'materials/metals',
  3312: 'materials/metals',
  3334: 'materials/metals',
  3357: 'materials/metals',

  // Industrials
  3812: 'industrials/defense',
  3760: 'industrials/defense',
  3795: 'industrials/defense',
  3721: 'industrials/aerospace',
  3724: 'industrials/aerospace',
  3713: 'industrials/machinery',
  3559: 'industrials/machinery',
  3540: 'industrials/machinery',
  3621: 'industrials/electrical',
  3640: 'industrials/electrical',
  3670: 'industrials/electrical',
  4011: 'industrials/transportation',
  4213: 'industrials/transportation',
  4512: 'industrials/transportation',
  4513: 'industrials/transportation',
  4731: 'industrials/transportation',

  // Tech
  3674: 'tech/semiconductors',
  7372: 'tech/software',
  7370: 'tech/software',
  7371: 'tech/software',
  7374: 'tech/software',
  3571: 'tech/hardware',
  3572: 'tech/hardware',
  3576: 'tech/hardware',
  3669: 'tech/hardware',
  7389: 'tech/cloud',

  // Financials
  6020: 'financials/banks',
  6021: 'financials/banks',
  6022: 'financials/banks',
  6029: 'financials/banks',
  6311: 'financials/insurance',
  6321: 'financials/insurance',
  6331: 'financials/insurance',
  6411: 'financials/insurance',
  6770: 'financials/asset_mgmt',
  6199: 'financials/asset_mgmt',
  6282: 'financials/asset_mgmt',
  6200: 'financials/exchanges',

  // Healthcare
  2836: 'healthcare/biotech',
  2834: 'healthcare/pharma',
  2833: 'healthcare/pharma',
  3841: 'healthcare/devices',
  3845: 'healthcare/devices',
  3826: 'healthcare/devices',
  8731: 'healthcare/biotech',

  // Consumer
  5961: 'consumer/retail',
  5331: 'consumer/retail',
  5411: 'consumer/staples',
  5651: 'consumer/retail',
  5712: 'consumer/retail',
  5734: 'consumer/retail',
  5912: 'consumer/staples',
  5990: 'consumer/retail',
  2080: 'consumer/staples',
  2086: 'consumer/staples',
  2090: 'consumer/staples',
  2111: 'consumer/staples',
  2300: 'consumer/discretionary',
  2320: 'consumer/discretionary',
  2390: 'consumer/discretionary',
  3140: 'consumer/discretionary',
  3711: 'consumer/discretionary', // Motor Vehicles & Car Bodies (autos OEM)

  // Utilities
  4911: 'utilities/power',
  4931: 'utilities/power',

  // Real Estate
  6798: 'real_estate/reits',
  6500: 'real_estate/reits',
  6512: 'real_estate/reits',
}

// FMP industry → bucket (补充 SIC 不准的 case)
// Combined legacy + 2025-taxonomy names. Each label appears once.
export const FMP_INDUSTRY_TO_BUCKET: Record<string, IndustryBucket> = {
  // ===== Energy =====
  'Oil & Gas Integrated': 'energy/oil_gas',
  'Oil & Gas - Integrated': 'energy/oil_gas',
  'Oil & Gas E&P': 'energy/oil_gas',
  'Oil & Gas - E&P': 'energy/oil_gas',
  'Oil & Gas Exploration & Production': 'energy/oil_gas',
  'Oil & Gas Refining & Marketing': 'energy/refining',
  'Oil & Gas - Refining & Marketing': 'energy/refining',
  'Oil & Gas Midstream': 'energy/midstream',
  'Oil & Gas - Midstream': 'energy/midstream',
  'Oil & Gas Equipment & Services': 'energy/services',
  'Oil & Gas - Equipment & Services': 'energy/services',
  'Oil & Gas Drilling': 'energy/services',
  'Oil & Gas - Drilling': 'energy/services',
  'Marine Shipping': 'energy/shipping',
  'Transportation - Marine Shipping': 'energy/shipping',
  'Marine': 'energy/shipping',
  'Thermal Coal': 'energy/oil_gas',
  'Coal': 'energy/oil_gas',
  'Uranium': 'utilities/power',

  // ===== Materials =====
  'Gold': 'materials/mining',
  'Silver': 'materials/mining',
  'Copper': 'materials/mining',
  'Other Industrial Metals & Mining': 'materials/mining',
  'Other Precious Metals & Mining': 'materials/mining',
  'Other Precious Metals': 'materials/mining',
  'Coal Mining': 'materials/mining',
  'Aluminum': 'materials/metals',
  'Steel': 'materials/metals',
  'Industrial Materials': 'materials/metals',
  'Manufacturing - Metal Fabrication': 'materials/metals',
  'Specialty Chemicals': 'materials/chemicals',
  'Chemicals': 'materials/chemicals',
  'Chemicals - Specialty': 'materials/chemicals',
  'Construction Materials': 'materials/chemicals',
  'Lumber & Wood Production': 'materials/chemicals',
  'Paper & Paper Products': 'materials/chemicals',
  'Building Materials': 'materials/chemicals',
  'Paper, Lumber & Forest Products': 'materials/chemicals',
  'Agricultural Inputs': 'materials/agriculture',
  'Chemicals - Agricultural': 'materials/agriculture',

  // ===== Industrials =====
  'Aerospace & Defense': 'industrials/defense',
  'Defense': 'industrials/defense',
  'Aerospace': 'industrials/aerospace',
  'Specialty Industrial Machinery': 'industrials/machinery',
  'Industrial - Machinery': 'industrials/machinery',
  'Industrial - Distribution': 'industrials/machinery',
  'Industrial - Pollution & Treatment Controls': 'industrials/machinery',
  'Industrial - Specialties': 'industrials/machinery',
  'Industrial - Infrastructure Operations': 'industrials/machinery',
  'Industrial - Power Transmission': 'industrials/electrical',
  'Farm & Heavy Construction Machinery': 'industrials/machinery',
  'Agricultural - Machinery': 'industrials/machinery',
  'Industrial Distribution': 'industrials/machinery',
  'Tools & Accessories': 'industrials/machinery',
  'Manufacturing - Tools & Accessories': 'industrials/machinery',
  'Manufacturing - Miscellaneous': 'industrials/machinery',
  'Construction': 'industrials/machinery',
  'Engineering & Construction': 'industrials/machinery',
  'Conglomerates': 'industrials/machinery',
  'Waste Management': 'industrials/machinery',
  'Pollution & Treatment Controls': 'industrials/machinery',
  'Security & Protection Services': 'industrials/machinery',
  'Staffing & Employment Services': 'industrials/machinery',
  'Rental & Leasing Services': 'industrials/machinery',
  'Business Equipment & Supplies': 'industrials/machinery',
  'Specialty Business Services': 'industrials/machinery',
  'Consulting Services': 'tech/cloud',
  'Electrical Equipment & Parts': 'industrials/electrical',
  'Railroads': 'industrials/transportation',
  'Trucking': 'industrials/transportation',
  'Integrated Freight & Logistics': 'industrials/transportation',
  'Logistics & Distribution': 'industrials/transportation',
  'Airlines': 'industrials/transportation',
  'Airports & Air Services': 'industrials/transportation',
  'Transportation - Airlines': 'industrials/transportation',
  'Transportation - Railroads': 'industrials/transportation',
  'Transportation - Trucking': 'industrials/transportation',
  'Transportation - Logistics': 'industrials/transportation',
  'Airlines, Airports & Air Services': 'industrials/transportation',

  // ===== Tech =====
  'Semiconductors': 'tech/semiconductors',
  'Semiconductor Equipment & Materials': 'tech/semiconductors',
  'Software - Infrastructure': 'tech/software',
  'Software - Application': 'tech/software',
  'Software - Services': 'tech/software',
  'Computer Hardware': 'tech/hardware',
  'Consumer Electronics': 'tech/hardware',
  'Electronic Components': 'tech/hardware',
  'Electronics & Computer Distribution': 'tech/hardware',
  'Communication Equipment': 'tech/hardware',
  'Telecommunications Equipment': 'tech/hardware',
  'Hardware, Equipment & Parts': 'tech/hardware',
  'Technology Distributors': 'tech/hardware',
  'Information Technology Services': 'tech/cloud',
  'Internet Content & Information': 'tech/internet',
  'Internet Retail': 'consumer/retail',     // spec: "重复 · 后定义优先" → consumer/retail
  'Solar': 'utilities/renewables',
  'Scientific & Technical Instruments': 'tech/hardware',
  'Telecommunications Services': 'tech/internet',
  'Telecom Services': 'tech/internet',

  // ===== Financials =====
  'Banks - Diversified': 'financials/banks',
  'Banks - Regional': 'financials/banks',
  'Banks—Diversified': 'financials/banks',
  'Banks—Regional': 'financials/banks',
  'Banks': 'financials/banks',
  'Insurance - Diversified': 'financials/insurance',
  'Insurance—Diversified': 'financials/insurance',
  'Insurance - Property & Casualty': 'financials/insurance',
  'Insurance—Property & Casualty': 'financials/insurance',
  'Insurance - Life': 'financials/insurance',
  'Insurance—Life': 'financials/insurance',
  'Insurance - Reinsurance': 'financials/insurance',
  'Insurance—Reinsurance': 'financials/insurance',
  'Insurance - Specialty': 'financials/insurance',
  'Insurance Brokers': 'financials/insurance',
  'Insurance - Brokers': 'financials/insurance',
  'Asset Management': 'financials/asset_mgmt',
  'Capital Markets': 'financials/asset_mgmt',
  'Credit Services': 'financials/asset_mgmt',
  'Mortgage Finance': 'financials/asset_mgmt',
  'Financial Conglomerates': 'financials/asset_mgmt',
  'Financial Data & Stock Exchanges': 'financials/exchanges',
  'Financial - Capital Markets': 'financials/asset_mgmt',
  'Financial - Credit Services': 'financials/asset_mgmt',
  'Financial - Mortgages': 'financials/asset_mgmt',
  'Financial - Conglomerates': 'financials/asset_mgmt',
  'Financial - Diversified': 'financials/asset_mgmt',
  'Financial - Data & Stock Exchanges': 'financials/exchanges',
  'Investment - Banking & Investment Services': 'financials/asset_mgmt',
  'Shell Companies': 'financials/asset_mgmt',

  // ===== Healthcare =====
  'Drug Manufacturers - General': 'healthcare/pharma',
  'Drug Manufacturers—General': 'healthcare/pharma',
  'Drug Manufacturers - Specialty & Generic': 'healthcare/pharma',
  'Drug Manufacturers—Specialty & Generic': 'healthcare/pharma',
  'Biotechnology': 'healthcare/biotech',
  'Medical Devices': 'healthcare/devices',
  'Medical Instruments & Supplies': 'healthcare/devices',
  'Medical - Devices': 'healthcare/devices',
  'Medical - Instruments & Supplies': 'healthcare/devices',
  'Medical - Equipment & Services': 'healthcare/devices',
  'Medical Care Facilities': 'healthcare/pharma',
  'Medical - Care Facilities': 'healthcare/pharma',
  'Medical Distribution': 'healthcare/pharma',
  'Medical - Distribution': 'healthcare/pharma',
  'Health Information Services': 'healthcare/pharma',
  'Medical - Healthcare Information Services': 'healthcare/pharma',
  'Healthcare Plans': 'healthcare/pharma',
  'Medical - Healthcare Plans': 'healthcare/pharma',
  'Medical - Pharmaceuticals': 'healthcare/pharma',
  'Medical - Specialties': 'healthcare/pharma',
  'Diagnostics & Research': 'healthcare/biotech',
  'Medical - Diagnostics & Research': 'healthcare/biotech',
  'Pharmaceutical Retailers': 'consumer/retail',

  // ===== Consumer =====
  'Specialty Retail': 'consumer/retail',
  'Apparel Retail': 'consumer/retail',
  'Apparel - Retail': 'consumer/retail',
  'Auto & Truck Dealerships': 'consumer/retail',
  'Auto - Dealerships': 'consumer/retail',
  'Auto Parts': 'consumer/discretionary',
  'Auto - Parts': 'consumer/discretionary',
  'Auto Manufacturers': 'consumer/discretionary',
  'Auto - Manufacturers': 'consumer/discretionary',
  'Auto - Recreational Vehicles': 'consumer/discretionary',
  'Discount Stores': 'consumer/retail',
  'Department Stores': 'consumer/retail',
  'Home Improvement Retail': 'consumer/retail',
  'Home Improvement': 'consumer/retail',
  'Luxury Goods': 'consumer/discretionary',
  'Footwear & Accessories': 'consumer/discretionary',
  'Apparel - Footwear & Accessories': 'consumer/discretionary',
  'Apparel Manufacturing': 'consumer/discretionary',
  'Apparel - Manufacturers': 'consumer/discretionary',
  'Manufacturing - Textiles': 'consumer/discretionary',
  'Personal Services': 'consumer/discretionary',
  'Personal Products & Services': 'consumer/discretionary',
  'Travel Services': 'consumer/discretionary',
  'Travel Lodging': 'consumer/discretionary',
  'Lodging': 'consumer/discretionary',
  'Restaurants': 'consumer/discretionary',
  'Resorts & Casinos': 'consumer/discretionary',
  'Gambling, Resorts & Casinos': 'consumer/discretionary',
  'Leisure': 'consumer/discretionary',
  'Gambling': 'consumer/discretionary',
  'Recreational Vehicles': 'consumer/discretionary',
  'Furnishings, Fixtures & Appliances': 'consumer/discretionary',
  'Packaging & Containers': 'consumer/discretionary',
  'Residential Construction': 'consumer/discretionary',
  'Education & Training Services': 'consumer/discretionary',
  'Beverages - Non-Alcoholic': 'consumer/staples',
  'Beverages—Non-Alcoholic': 'consumer/staples',
  'Beverages - Alcoholic': 'consumer/staples',
  'Beverages - Wineries & Distilleries': 'consumer/staples',
  'Beverages—Wineries & Distilleries': 'consumer/staples',
  'Beverages - Brewers': 'consumer/staples',
  'Beverages—Brewers': 'consumer/staples',
  'Confectioners': 'consumer/staples',
  'Food - Confectioners': 'consumer/staples',
  'Farm Products': 'consumer/staples',
  'Food - Farm Products': 'consumer/staples',
  'Agricultural Farm Products': 'consumer/staples',
  'Food Distribution': 'consumer/staples',
  'Food - Distribution': 'consumer/staples',
  'Grocery Stores': 'consumer/staples',
  'Household & Personal Products': 'consumer/staples',
  'Packaged Foods': 'consumer/staples',
  'Food - Packaged': 'consumer/staples',
  'Tobacco': 'consumer/staples',
  'Food Confectioners': 'consumer/staples',

  // ===== Utilities =====
  'Utilities - Regulated Electric': 'utilities/power',
  'Utilities—Regulated Electric': 'utilities/power',
  'Regulated Electric': 'utilities/power',
  'Utilities - Regulated Gas': 'utilities/power',
  'Utilities—Regulated Gas': 'utilities/power',
  'Regulated Gas': 'utilities/power',
  'Utilities - Regulated Water': 'utilities/power',
  'Utilities—Regulated Water': 'utilities/power',
  'Regulated Water': 'utilities/power',
  'Utilities - Diversified': 'utilities/power',
  'Utilities—Diversified': 'utilities/power',
  'Diversified Utilities': 'utilities/power',
  'Utilities - Independent Power Producers': 'utilities/power',
  'Utilities—Independent Power Producers': 'utilities/power',
  'Independent Power Producers': 'utilities/power',
  'Utilities - Renewable': 'utilities/renewables',
  'Utilities—Renewable': 'utilities/renewables',
  'Renewable Utilities': 'utilities/renewables',

  // ===== Real Estate =====
  'REIT - Diversified': 'real_estate/reits',
  'REIT—Diversified': 'real_estate/reits',
  'REIT - Industrial': 'real_estate/reits',
  'REIT—Industrial': 'real_estate/reits',
  'REIT - Office': 'real_estate/reits',
  'REIT—Office': 'real_estate/reits',
  'REIT - Retail': 'real_estate/reits',
  'REIT—Retail': 'real_estate/reits',
  'REIT - Residential': 'real_estate/reits',
  'REIT—Residential': 'real_estate/reits',
  'REIT - Healthcare Facilities': 'real_estate/reits',
  'REIT—Healthcare Facilities': 'real_estate/reits',
  'REIT - Hotel & Motel': 'real_estate/reits',
  'REIT—Hotel & Motel': 'real_estate/reits',
  'REIT - Mortgage': 'real_estate/reits',
  'REIT—Mortgage': 'real_estate/reits',
  'REIT - Specialty': 'real_estate/reits',
  'REIT—Specialty': 'real_estate/reits',
  'Real Estate Services': 'real_estate/reits',
  'Real Estate - Services': 'real_estate/reits',
  'Real Estate - Development': 'real_estate/reits',
  'Real Estate—Development': 'real_estate/reits',
  'Real Estate - Diversified': 'real_estate/reits',
  'Real Estate—Diversified': 'real_estate/reits',

  // ===== Media (folded into tech/internet) =====
  'Entertainment': 'tech/internet',
  'Broadcasting': 'tech/internet',
  'Publishing': 'tech/internet',
  'Advertising Agencies': 'tech/internet',
  'Electronic Gaming & Multimedia': 'tech/internet',
}

// Returns the union of buckets implied by SIC and FMP industry.
// Empty array means neither source matched any rule.
export function resolveBuckets(
  sic: number | null | undefined,
  fmpIndustry: string | null | undefined,
): IndustryBucket[] {
  const buckets = new Set<IndustryBucket>()
  if (typeof sic === 'number' && SIC_TO_BUCKET[sic]) {
    buckets.add(SIC_TO_BUCKET[sic])
  }
  if (fmpIndustry && FMP_INDUSTRY_TO_BUCKET[fmpIndustry]) {
    buckets.add(FMP_INDUSTRY_TO_BUCKET[fmpIndustry])
  }
  return Array.from(buckets)
}

// FMP-first primary bucket selection: prefer the FMP bucket if it differs
// from SEC (FMP industry tends to reflect current business better).
export function pickPrimaryBucket(
  sic: number | null | undefined,
  fmpIndustry: string | null | undefined,
): IndustryBucket | null {
  if (fmpIndustry && FMP_INDUSTRY_TO_BUCKET[fmpIndustry]) {
    return FMP_INDUSTRY_TO_BUCKET[fmpIndustry]
  }
  if (typeof sic === 'number' && SIC_TO_BUCKET[sic]) {
    return SIC_TO_BUCKET[sic]
  }
  return null
}
