-- Compressed bilingual headline for compact UI surfaces (timeline cards, alerts, etc).
-- Generated by Claude Haiku from `headline` + optional context.
-- Nullable: legacy rows + freshly-ingested rows that haven't run through the summarizer yet
-- fall back to the raw headline in the UI.

alter table events
  add column if not exists short_headline    text,
  add column if not exists short_headline_zh text;

create index if not exists events_short_headline_pending_idx
  on events (event_date desc)
  where short_headline is null;
